# Generated by Django 4.0.3 on 2022-04-10 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_type_remove_employee_name_employee_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.type'),
        ),
    ]
